### ISSUE TITLE
Set max cache/picture size/amount

### ISSUE THREAD

**Issue by scooterama** [andrasferenczi/vitrina-legacy#11]
the new version just adds pictures to the list when downloaded. 
My list is huge already without having the possibility to reset it. Please let us set a max amount of pictures and delete the oldest.

**Comment by Prn-Ice** [comment]
The only reason I'm not using this right now. Posting just so I can be subscribed 😁.

**Comment by andrasferenczi** [comment]
I have created a version with a maximum of 16 images that you cannot set. Not closing this issue, because there is no UI for this.

See #17

**Comment by andrasferenczi** [comment]
This is fixed with the new version. More info at #21
