### ISSUE TITLE
Method to handle image when aspect ratio does not match screen size

### ISSUE THREAD

**Issue by theabhishek2511** [andrasferenczi/vitrina-legacy#23]
I usually only use one launcher screen on my Google Pixel 3a, and it appears that Vitrina does not like it, as most images end up left-aligned.

[Screenshot from app showing full image](https://files.catbox.moe/abxwsr.png), and [how the image appears on the home page.](https://files.catbox.moe/w1stsv.png) 

An ability to control this behaviour would be nice, unless I've missed it somewhere.

**Comment by andrasferenczi** [comment]
I've just implemented your request. There will be a checkbox in the next update to ensure the wallpaper is aligned to center, in which case the renderer will ignore the offset values from the launcher.

It will be released in a day or so.
