### ISSUE TITLE
Image ratio restriction

### ISSUE THREAD

**Issue by andrasferenczi** [andrasferenczi/vitrina-legacy#3]
Let users specify a minimum image ratio.

Problems:
- Should work in both ways (`ratio = width / height`)
    - define a ratio
    - define which way is acceptable (less or more)

Idea for user interface:

- specify ratio (width/height)
- `allow wider` checkbox
- `allow taller` checkbox

**Comment by Crono141** [comment]
Silly me, I just opened a new issue requesting exactly this.  I'll remove it.  Please consider making this update soon.  Thanks.

**Comment by andrasferenczi** [comment]
This is added in the premium version of the new release. More info at #21
