### ISSUE TITLE
Can't remove subreddit

### ISSUE THREAD

**Issue by TBog** [andrasferenczi/vitrina-legacy#6]
Once I figured out where to write the new subreddit name when I want to add one I was stuck with the defaut subreddits

in version 1.0.29

**Comment by andrasferenczi** [comment]
You can remove any subreddit by swiping the list item to the left.

**Comment by TBog** [comment]
Thanks, it worked, there should be a tutorial or at least a few words on first launch or on the github page

**Comment by andrasferenczi** [comment]
Added infos on the Github page, thanks for creating the issue

**Comment by scooterama** [comment]
I came here because I felt like I did swipe in any direction (except left) and couldn't find "delete". Please just add a trash-button.

**Comment by andrasferenczi** [comment]
UI is completely rewritten. See #21 for more info
